
----CRIACAO DO BANCO DB_AULA
--CREATE DATABASE DB_AULA

----CRIAÇÃO DO BANCO DBTESTE
--CREATE DATABASE dbteste
----EXCLUSÃO DO BANCO DBTESTE 
--DROP DATABASE dbteste

----SELECIONAR O BANCO DE DADOS QUE VOCE VAI TRABALHAR
USE DB_AULA

--DROP DATABASE DB_AULA

CREATE TABLE ALUNO(
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(150) NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    OBS VARCHAR(500)
)

ALTER TABLE ALUNO
ADD CPF VARCHAR(11)

ALTER TABLE ALUNO
DROP COLUMN OBS

CREATE TABLE TELEFONE(
    ID INT PRIMARY KEY IDENTITY(5,1), --PRIMEIRO PARAMETRO É O VALOR INICIAL, SEGUNDO PARAMETRO É O INCREMENTO
    TELEFONE VARCHAR(11),
    ID_ALUNO INT REFERENCES ALUNO(ID),
    UNIQUE (TELEFONE, ID_ALUNO)
)

CREATE TABLE EMAIL(
    EMAIL VARCHAR(200), 
    ID_ALUNO INT REFERENCES ALUNO(ID),
    PRIMARY KEY (EMAIL, ID_ALUNO)
)

-- DROP TABLE TELEFONE
-- DROP TABLE EMAIL
-- DROP TABLE ALUNO



-- INSERT INTO ALUNO (ID, NOME, DATA_CADASTRO, CPF) VALUES (1, 'ARTHUR ', '2026-01-01', '123456')
-- INSERT INTO ALUNO VALUES (2, 'MARCOS', '2026-01-01', '123456')
-- INSERT INTO ALUNO VALUES (3, 'ANA', NULL, '123456')
-- INSERT INTO ALUNO (ID, NOME, CPF) VALUES (4, 'MARIA', '123456')
-- INSERT INTO ALUNO VALUES (5, 'JOAO', '', '123456')
-- INSERT INTO ALUNO VALUES (6, 'MARIO', '', '123456')


INSERT INTO ALUNO ( NOME, DATA_CADASTRO, CPF) VALUES ( 'ARTHUR ', '2026-01-01', '123456')
INSERT INTO ALUNO VALUES ( 'MARCOS', '2026-01-01', '123456')
INSERT INTO ALUNO VALUES ( 'ANA', NULL, '123456')
INSERT INTO ALUNO ( NOME, CPF) VALUES ( 'MARIA', '123456')
INSERT INTO ALUNO VALUES ( 'JOAO', '', '123456')
INSERT INTO ALUNO VALUES ( 'MARIO', '', '123456')
INSERT INTO ALUNO VALUES ( NULL, '', '123456')
INSERT INTO ALUNO VALUES ( 'ANTONIO', '', '123456')

--INSERINDO MULTIPLOS ALUNOS DE UMA VEZ
INSERT INTO ALUNO ( NOME, DATA_CADASTRO, CPF) VALUES
('ALUNO 1', '2026-01-01', '123456'),
('ALUNO 2', '2026-01-01', '123456'),
('ALUNO 3', '2026-01-01', '123456'),
('ALUNO 4', '2026-01-01', '123456')


INSERT INTO TELEFONE VALUES ('123456789',1)
INSERT INTO TELEFONE VALUES ('123456789',1)
INSERT INTO TELEFONE VALUES ('123456789',2)

INSERT INTO EMAIL VALUES ('EMAIL@ARTUR', 1)
INSERT INTO EMAIL VALUES ('EMAIL@ARTUR', 1)
INSERT INTO EMAIL VALUES ('EMAIL@ARTUR', 2)

SELECT * FROM ALUNO
SELECT * FROM TELEFONE
SELECT * FROM EMAIL


UPDATE ALUNO 
SET NOME = 'CAIO'
WHERE ID = 9

UPDATE ALUNO 
SET NOME = 'MARLON'
WHERE NOME = 'ALUNO 2'

UPDATE ALUNO 
SET NOME = 'REBERT', 
    DATA_CADASTRO = '2026-02-01', 
    CPF = '123456789'
WHERE NOME = 'ALUNO 3'



UPDATE ALUNO 
SET NOME = 'ARTHUR O ESTAG'
WHERE NOME = 'ALUNO 4'

UPDATE ALUNO 
SET NOME = 'NOME FIXO'
WHERE ID >= 1 AND ID <= 5


BEGIN TRANSACTION

    UPDATE ALUNO 
    SET NOME = 'ALTERACAO '
    WHERE ID = 1
    

COMMIT
ROLLBACK 
