--CREATE DATABASE DB_LOJA
GO

USE DB_LOJA


CREATE TABLE ENDERECOS(
    ID INT PRIMARY KEY IDENTITY(1,1), 
    PAIS NVARCHAR(20),
    ESTADO NVARCHAR(50),
    CIDADE NVARCHAR(80), 
    ENDERECO NVARCHAR(200), 
    CEP VARCHAR(8)
)
--DROP TABLE ENDERECO

CREATE TABLE CLIENTES(
    ID INT PRIMARY KEY IDENTITY(1,1), 
    CPF VARCHAR(11) NOT NULL,
    NOME NVARCHAR(200) NOT NULL, 
    COMPLETO NVARCHAR(150), 
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    ID_ENDERECO INT REFERENCES ENDERECOS(ID)
)
