USE DB_LOJA
GO 


SELECT * FROM CLIENTES AS C
LEFT JOIN ENDERECOS AS E ON E.ID = C.ID_ENDERECO
LEFT JOIN CLIENTES_TELEFONES AS CT ON CT.ID_CLIENTE = C.ID

SELECT * FROM CLIENTES AS C
LEFT JOIN CLIENTES_EMAILS AS CE ON CE.ID_CLIENTE = C.ID 


SELECT * FROM CLIENTES AS C
INNER JOIN PEDIDOS AS P ON P.ID_CLIENTE = C.ID


SELECT * FROM PEDIDOS AS P
LEFT JOIN PRODUTOS_X_PEDIDO AS PP ON PP.ID_PEDIDO = P.ID
LEFT JOIN PRODUTOS AS PR ON PR.ID = PP.ID_PRODUTO
WHERE P.ID = 10


SELECT * FROM FUNCIONARIOS AS F
INNER JOIN PEDIDOS AS P ON P.ID_FUNCIONARIO = F.MATRICULA
WHERE MATRICULA = 1003