--CREATE DATABASE DB_LOJA
GO

USE DB_LOJA


CREATE TABLE ENDERECOS(
    ID INT PRIMARY KEY IDENTITY(1,1), 
    PAIS NVARCHAR(20),
    ESTADO NVARCHAR(50),
    CIDADE NVARCHAR(80), 
    ENDERECO NVARCHAR(200), 
    CEP VARCHAR(8)
)
--DROP TABLE ENDERECO

CREATE TABLE CLIENTES(
    ID INT PRIMARY KEY IDENTITY(1,1), 
    CPF VARCHAR(11) NOT NULL,
    NOME NVARCHAR(200) NOT NULL, 
    COMPLETO NVARCHAR(150), 
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    ID_ENDERECO INT REFERENCES ENDERECOS(ID)
)

CREATE TABLE CLIENTES_TELEFONES(
    ID INT PRIMARY KEY IDENTITY(1,1),
    TELEFONE VARCHAR(11) NOT NULL,
    ID_CLIENTE INT REFERENCES CLIENTES(ID) 
)

CREATE TABLE CLIENTES_EMAILS(
    ID INT PRIMARY KEY IDENTITY(1,1),
    EMAIL VARCHAR(200) NOT NULL,
    ID_CLIENTE INT REFERENCES CLIENTES(ID) 
)

CREATE TABLE METODOS_PAGAMENTOS(
    ID INT PRIMARY KEY IDENTITY(1,1), 
    ID_CLIENTE INT REFERENCES CLIENTES (ID), 
    TIPO VARCHAR(50),
    NUMERO VARCHAR(16), 
    BANDEIRA  VARCHAR(15)
)

CREATE TABLE FORNECEDORES (
    ID INT PRIMARY KEY IDENTITY(1,1), 
    CNPJ VARCHAR(14), 
    RAZAO_SOCIAL NVARCHAR(150),
    REGIME_TRIBUTARIO VARCHAR (50), 
    ID_ENDERECO INT REFERENCES ENDERECOS(ID), 
    COMPLETO NVARCHAR(150) 
)
CREATE TABLE FORNECEDORES_TELEFONES(
    TELEFONE VARCHAR(11) NOT NULL,
    ID_FORNECEDOR INT REFERENCES FORNECEDORES(ID) 
    PRIMARY KEY (TELEFONE, ID_FORNECEDOR)
)

CREATE TABLE FUNCIONARIOS (
    MATRICULA INT PRIMARY KEY, 
    CTPS VARCHAR(14), 
    NOME NVARCHAR(150),
    CARGO VARCHAR (50), 
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    ID_ENDERECO INT REFERENCES ENDERECOS(ID), 
    COMPLETO NVARCHAR(150) 
)
CREATE TABLE FUNCIONARIOS_TELEFONES(
    TELEFONE VARCHAR(11) NOT NULL,
    ID_FUNCIONARIOS INT REFERENCES FUNCIONARIOS(MATRICULA) 
    PRIMARY KEY (TELEFONE, ID_FUNCIONARIOS)
)

CREATE TABLE PRODUTOS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    NOME NVARCHAR(150), 
    ESPECICACAO NVARCHAR(200), 
    PRECO DECIMAL, 
    QUANTIDADE INT, 
    PRECO_CUSTO DECIMAL, 
    PESO DECIMAL, 
    ID_FORNECEDOR  INT REFERENCES FORNECEDORES(ID)
)


CREATE TABLE AVALIACAO ( 
    ID INT PRIMARY KEY IDENTITY(1,1),
    ID_CLIENTE INT REFERENCES CLIENTES(ID), 
    ID_PRODUTOR INT REFERENCES PRODUTOS(ID),
    NOTA INT NOT NULL, 
    DESCRICAO NVARCHAR(300) 
)

CREATE TABLE PEDIDOS (
    ID INT PRIMARY KEY IDENTITY(1,1), 
    ID_CLIENTE INT REFERENCES CLIENTES(ID), 
    ID_FUNCIONARIO INT REFERENCES FUNCIONARIOS(MATRICULA),
    FRETE DECIMAL, 
    VALOR_TOTAL DECIMAL, 
    IMPOSTO DECIMAL,
    QUANTIDADE_ITENS INT, 
    COMPLEMENTO NVARCHAR(150), 
    ID_ENDERECO INT REFERENCES ENDERECOS(ID)
)

CREATE TABLE PRODUTOS_X_PEDIDO(
    ID_PEDIDO INT REFERENCES PEDIDOS(ID), 
    ID_PRODUTO INT REFERENCES PRODUTOS(ID), 
    QUANTIDADE INT DEFAULT 1, 
    VALOR_UNITARIO DECIMAL, 
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO)
)

CREATE TABLE PGMT_X_PEDIDOS(
    ID_PAGAMENTO INT REFERENCES METODOS_PAGAMENTOS(ID), 
    ID_PEDIDO INT REFERENCES PEDIDOS(ID), 
    PRIMARY KEY (ID_PAGAMENTO, ID_PEDIDO)
)